### PR TITLE
Added a Screenshot

### PR DESCRIPTION
**Pull request by navintc**
Uploaded a screenshot of hare running on haiku
Added the screenshot in to the readme.md

### CODE REVIEW

**Comment by humdingerb** [comment]
Is it possible to make the window smaller? That way wouldn't have to be displayed resized, and therefore slightly fuzzy.

**Comment by navintc** [comment]
No, tried to make it smaller. Actually the window should be much larger. As you can see in this screenshot the "genre" textbox is not visible. If I resize this into a much smaller window, they might not appear. Is there something I can do to make it small while making everything visible?

**Comment by humdingerb** [comment]
OK. Nothing much you can do. The GUI needs work...

**Comment by scottmc** [comment]
The GUI needs much work, but that's another task. ;)

**Pull request merged**
