### PR TITLE
Style fixes according to Haiku coding style guidelines

### PR DESCRIPTION
**Pull request by CodeforEvolution**
Hello! I'd like to finally look again at layouting Hare, but first I got in some style fixes according to the Haiku coding style guidelines.

### CODE REVIEW

**Comment by waddlesplash** [comment]
Thanks!

FWIW, it's probably a good idea to move off of libsanta before you attempt layouting.

**Comment by CodeforEvolution** [comment]
Alright, also, would it be ok to convert Hare to use the Makefile-Engine, or just keep the CMake build system. Also, could I remove the remains of the old Makefile system?

**Comment by waddlesplash** [comment]
Yes and yes.

**Comment by smccrearyx** [comment]
What waddlesplash said.  Yes drop libsanta, and move to layout.  And drop cmake in favor of makefile-engine, and removing any left over cruft from previous one.

**Pull request merged**
